language: node_js
node_js:
  - stable
  - '0.12'
sudo: false
deploy:
  provider: npm
  email: pattyn.kurt@gmail.com
  api_key:
    secure: LQBD1bwr0zPu9IC0Xpjb3E+BO+pC8+1L4N+OarmEszhq+MnQboFBjdHDc+Kl7EhfaBy293hyTV6bxNtL5Pr6+69DxhgmwqH/JMvy9/cDDhjX0OLEBBWLxNRn7iLIZ46oUQ9ZX8EDUXmQkCfINWRDYvYKDr3KiLBC3A+VlJCU9zai2aLUP6+uONllH+54ZFHNVptHnl7HoiJozhtFl8f68qVvhtgbHFLDangB290RIIcv2JsM1x+e24qT1tEd3ovg0PTFRy0BhR16J9va4qnIVG/DSFBnCY9CY4ewn4fU8YLB3wDk4b67zvcxDZEEdcSxHDDn/egTZp1xkVzRlQNNepTEVcNdb5No511IDFd2/UyXGWtHxh/uk/kIwP3cuEOnDd+wwgBqpAYC70hNXsqrQ1xs9+8PpAxWdF/cN9kpKsQ9cnET1o9fi73mz3deM8GxK3gPZTpRjf/R6/XFmYZ0J4M6bJeu+NjoOC9X5ZWAGV5cm6cUyV9m/rSOPhFkS2iMsFvcGYdoUoPr0/J1g/jORB8zpCCviblpIoMpVy2tpIhXb9cWqVcVs65T4ZgDrHftNjH/eEpkOrqGj/vsC6DEH52/+Q+RGWkbTUq+jXKbOlqgn9/jvOdVEZcu1h82yF2fm3OaM4r9AljB8UN4QAHCo1nDo9TaP7mg0I8rAjbltBE=
  on:
    tags: true
    repo: KurtPattyn/konsol
    branch: master
addons:
  code_climate:
    repo_token:
      secure: SA2R5bCS4qRVssSGaWRF9uJ5PodzYvk19MbWsAC+G8Cl0/pjcJ1rj7VhY0LL/sHjr5vX/bILCNNIunYucc2bCZ5L3PToxybDazWTTbhCfeHxj0CLlwnYpea9Q/Qk2ydRnPTdYUIsTBzDsHxLVUaCu6sl5v2f2Dhl2XiP/5VrOjjGYBMgghc6jVXfgqoeh7lDQACtfuPs1V+brGCNEiPh7snA/5FRowGu8+cyGZ9mkPZy+FlJsohaKa9X275GA1BvovLfYRlgfVu7anWbiYYeEIag7pJsCY5QQFnzseBUFnLfQ+JLD+NR5dee85H1/KJ3jfRdlDjTA7qfbl85cQPD2UaN0jOh15iFpRE2oWV9HGfjCIVJYyeRSLM/gVvk6cyIUqAHtIcNNjxieD3MIxN4Kf9+xIfarwm5PLCYeOBbNZU3qcpmuUejGiTmCQPqGGc9MQCgROCF2nu8Owl8i2SZsmvTF3r6F7VTm/A3H/V8JeuITkImXrUIE4m1CpOKeNYPDR49R6kAIN0MA7FE0okPfYPDKxihN9BMxFB9VRN/ulN+8jWW4stFogRGWhvCCpXGwGzHDElFfIFy0hB6tZLJoCoUn2/o7mg3E5o16fWjfr7DTsQftSqAon5OH7MM17/Giamdbxsr58ChhKEnZsZ0deWDM3B/6N5yhzd138zFJYQ=
before_script:
  - npm run check-style
  - npm run code-analysis
script:
  - npm run test-ci
  - npm run check-coverage
after_success:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
  - npm install codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info
